/// <reference types="cypress" />

describe('Cyprompt Demo', () => {

    let username;
    let password;
    let email;

    before(() => {
        username = Cypress.env('username');
        password = Cypress.env('password');
        email = Cypress.env('email');
    });

    it('Use cy.prompt to register a new user', () => {
        cy.prompt(
            [
                'Visit http://eaapp.somee.com/',
                'Click the Register button',
                `Type username as ${username} in the Username field`,
                `Type a password as ${password} in the Password field`,
                `Type the same password ${password} in the Confirm Password field`,
                `Type valid email address as ${email} in the Email field`,
                'Click the Register button to complete registration',
                'Verify we are redirected to the dashboard by checking for "About" text on the page'
            ]
        )
    });

    it('Use cy.prompt to login with existing user and verify the employee table', () => {
        cy.prompt(
            [
                'Visit http://eaapp.somee.com/',
                'Click the Login button',
                `Type username as ${username}in the Username field`,
                `Type password as ${password} in the Password field`,
                'Click the Login button to login',
                'Verify we are redirected to the dashboard by checking for "About" text on the page',
                'Click on Employee List link from the top navigation menu',
                'Verify we are on Employee List page by checking the url contains "Employee"',
                'Verify the Employee List table is visible',
                'Verify the employee "John" is present in the table'
            ]
        )

        /* Code generated by cy.prompt for the test above
            Prompt step 1: Visit http://eaapp.somee.com/
            cy.visit("http://eaapp.somee.com/");
    
            Prompt step 2: Click the Login button
            cy.get("#loginLink").click()
    
            Prompt step 3: Type username as usercpopndin the Username field
            cy.get("[name=\"UserName\"]").type("usercpopnd")
    
            Prompt step 4: Type password as Hn9nay19! in the Password field
            cy.get("[name=\"Password\"]").type("Hn9nay19!")
    
            Prompt step 5: Click the Login button to login
            cy.get("#loginIn").click()
    
            Prompt step 6: Verify we are redirected to the dashboard by checking for "About" text on the page
            cy.get("div:nth-child(1) h2").should("be.visible")
    
            Prompt step 7: Click on Employee List link from the top navigation menu
            cy.get("a[href=\"/Employee\"]").click()
    
            Prompt step 8: Verify we are on Employee List page by checking the url contains "Employee"
            cy.url().should("contain", "Employee")
    
            Prompt step 9: Verify the Employee List table is visible
            cy.get("table.table").should("be.visible")
    
            Prompt step 10: Verify the employee "John" is present in the table
            cy.get("table.table").should("contain", "John")     
        */

    });
});